name 'theforeman'
maintainer       'LLC Express 42'
maintainer_email 'cookbooks@express42.com'
license          'MIT'
description 'Installs/Configures theforeman'
long_description 'Installs/Configures theforeman'
version '1.0.2'

depends 'postgresql_lwrp'
depends 'memcached'
depends 'nginx'
